// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nordik_Aventure;

#nullable disable

namespace Nordik_Aventure.Migrations
{
    [DbContext(typeof(NordikAventureContext))]
    [Migration("20251111211424_AjouterPremierfournisseurEtPremierProduit")]
    partial class AjouterPremierfournisseurEtPremierProduit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PaybackToSupplier")
                        .HasColumnType("double");

                    b.Property<double>("PriceToBuy")
                        .HasColumnType("double");

                    b.Property<double>("PriceToSell")
                        .HasColumnType("double");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tente légère 2 places",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 145.0,
                            PriceToSell = 299.0,
                            Sku = "NC-TNT-001",
                            Status = "Actif",
                            SupplierId = 1,
                            Weight = 2.7999999999999998
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AverageDeliveryTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDeliveryTime = "1 jour",
                            Code = "AX",
                            Discount = 0,
                            Name = "AventureX"
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.User.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tentes & abris"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sacs & portage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vetements techniques"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accessoires & cuisine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Electronique & navigation"
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.User.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SatisfactionLevel")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "144 rue de paul, Lévis, Qc, Canada",
                            Email = "paul@paul.ca",
                            Name = "Paul",
                            Password = "Paul123",
                            Phone = "418-878-4090",
                            Type = "particulier"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 rue du kayak, Montréal, Qc, Canada",
                            Email = "kayak@kayak.ca",
                            Name = "KayakManiac",
                            Password = "Kayak123",
                            Phone = "418-878-4990",
                            Type = "entreprise"
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.User.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "marc123@gmail.com",
                            HireDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Marc",
                            Password = "marc123*",
                            PhoneNumber = "418-882-8636",
                            Role = "Employee",
                            Surname = "Leblond"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "jean123@gmail.com",
                            HireDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Jean",
                            Password = "jean123*",
                            PhoneNumber = "418-882-8646",
                            Role = "Manager",
                            Surname = "Laronde"
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "money@gmail.com",
                            HireDate = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Arjean",
                            Password = "money123*",
                            PhoneNumber = "418-182-8646",
                            Role = "Accountant",
                            Surname = "Labonde"
                        });
                });

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.Product", b =>
                {
                    b.HasOne("Nordik_Aventure.Objects.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("ProductCategories", b =>
                {
                    b.HasOne("Nordik_Aventure.Objects.Models.User.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nordik_Aventure.Objects.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
