// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nordik_Aventure;

#nullable disable

namespace Nordik_Aventure.Migrations
{
    [DbContext(typeof(NordikAventureContext))]
    [Migration("20251117184950_gross-margin-add")]
    partial class grossmarginadd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<double>("GrossMargin")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PaybackToSupplier")
                        .HasColumnType("double");

                    b.Property<double>("PriceToBuy")
                        .HasColumnType("double");

                    b.Property<double>("PriceToSell")
                        .HasColumnType("double");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            GrossMargin = 51.5,
                            Name = "Tente légère 2 places",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 145.0,
                            PriceToSell = 299.0,
                            Sku = "NC-TNT-001",
                            Status = "Actif",
                            SupplierId = 1,
                            Weight = 2.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            GrossMargin = 47.899999999999999,
                            Name = "Tente familiale 6 places",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 260.0,
                            PriceToSell = 499.0,
                            Sku = "NC-TNT-002",
                            Status = "Actif",
                            SupplierId = 1,
                            Weight = 6.5
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            GrossMargin = 57.600000000000001,
                            Name = "Toile imperméable 3x3 m",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 25.0,
                            PriceToSell = 59.0,
                            Sku = "NC-TNT-003",
                            Status = "Actif",
                            SupplierId = 2,
                            Weight = 1.1000000000000001
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            GrossMargin = 53.799999999999997,
                            Name = "Tapis de sol isolant",
                            PaybackToSupplier = 0.029999999999999999,
                            PriceToBuy = 18.0,
                            PriceToSell = 39.0,
                            Sku = "NC-TNT-004",
                            Status = "Actif",
                            SupplierId = 3,
                            Weight = 0.90000000000000002
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            GrossMargin = 49.700000000000003,
                            Name = "Abri cuisine pliable",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 75.0,
                            PriceToSell = 149.0,
                            Sku = "NC-TNT-005",
                            Status = "Actif",
                            SupplierId = 1,
                            Weight = 5.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            GrossMargin = 58.600000000000001,
                            Name = "Mat telescopique alu",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 12.0,
                            PriceToSell = 29.0,
                            Sku = "NC-TNT-006",
                            Status = "Actif",
                            SupplierId = 2,
                            Weight = 0.69999999999999996
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            GrossMargin = 53.200000000000003,
                            Name = "Sac à dos 50 L etanche",
                            PaybackToSupplier = 0.059999999999999998,
                            PriceToBuy = 65.0,
                            PriceToSell = 139.0,
                            Sku = "NC-SAC-001",
                            Status = "Actif",
                            SupplierId = 4,
                            Weight = 1.3
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            GrossMargin = 59.5,
                            Name = "Sac de jour 25 L",
                            PaybackToSupplier = 0.059999999999999998,
                            PriceToBuy = 32.0,
                            PriceToSell = 79.0,
                            Sku = "NC-SAC-002",
                            Status = "Actif",
                            SupplierId = 4,
                            Weight = 0.90000000000000002
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            GrossMargin = 52.700000000000003,
                            Name = "Sac de couchage -10 degree",
                            PaybackToSupplier = 0.029999999999999999,
                            PriceToBuy = 80.0,
                            PriceToSell = 169.0,
                            Sku = "NC-SAC-003",
                            Status = "Actif",
                            SupplierId = 3,
                            Weight = 2.2000000000000002
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            GrossMargin = 57.600000000000001,
                            Name = "Tapis autogonflant",
                            PaybackToSupplier = 0.029999999999999999,
                            PriceToBuy = 25.0,
                            PriceToSell = 59.0,
                            Sku = "NC-SAC-004",
                            Status = "Actif",
                            SupplierId = 3,
                            Weight = 1.1000000000000001
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            GrossMargin = 52.600000000000001,
                            Name = "Housse impermeable sac a dos",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 9.0,
                            PriceToSell = 19.0,
                            Sku = "NC-SAC-005",
                            Status = "Actif",
                            SupplierId = 2,
                            Weight = 0.40000000000000002
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            GrossMargin = 55.700000000000003,
                            Name = "Batons de marche carbone",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 35.0,
                            PriceToSell = 79.0,
                            Sku = "NC-SAC-006",
                            Status = "Actif",
                            SupplierId = 2,
                            Weight = 0.80000000000000004
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            GrossMargin = 62.700000000000003,
                            Name = "Chandail thermique homme",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 22.0,
                            PriceToSell = 59.0,
                            Sku = "NC-VET-001",
                            Status = "Actif",
                            SupplierId = 5,
                            Weight = 0.59999999999999998
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            GrossMargin = 62.700000000000003,
                            Name = "Chandail thermique femme",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 22.0,
                            PriceToSell = 59.0,
                            Sku = "NC-VET-002",
                            Status = "Actif",
                            SupplierId = 5,
                            Weight = 0.59999999999999998
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            GrossMargin = 57.299999999999997,
                            Name = "Pantalon de randonnee homme",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 38.0,
                            PriceToSell = 89.0,
                            Sku = "NC-VET-003",
                            Status = "Actif",
                            SupplierId = 5,
                            Weight = 0.80000000000000004
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            GrossMargin = 57.299999999999997,
                            Name = "Pantalon de randonnee femme",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 38.0,
                            PriceToSell = 89.0,
                            Sku = "NC-VET-004",
                            Status = "Actif",
                            SupplierId = 5,
                            Weight = 0.80000000000000004
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            GrossMargin = 57.399999999999999,
                            Name = "Manteau coupe-vent",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 55.0,
                            PriceToSell = 129.0,
                            Sku = "NC-VET-005",
                            Status = "Actif",
                            SupplierId = 6,
                            Weight = 1.1000000000000001
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            GrossMargin = 65.5,
                            Name = "Tuque en laine merinos",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 10.0,
                            PriceToSell = 29.0,
                            Sku = "NC-VET-006",
                            Status = "Actif",
                            SupplierId = 6,
                            Weight = 0.29999999999999999
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            GrossMargin = 60.0,
                            Name = "Gants isolants Hiver+",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 18.0,
                            PriceToSell = 45.0,
                            Sku = "NC-VET-007",
                            Status = "Actif",
                            SupplierId = 6,
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            GrossMargin = 57.600000000000001,
                            Name = "Rechaud portatif",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 25.0,
                            PriceToSell = 59.0,
                            Sku = "NC-ACC-001",
                            Status = "Actif",
                            SupplierId = 2,
                            Weight = 0.90000000000000002
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            GrossMargin = 58.600000000000001,
                            Name = "Bouteille isotherme 1L",
                            PaybackToSupplier = 0.029999999999999999,
                            PriceToBuy = 12.0,
                            PriceToSell = 29.0,
                            Sku = "NC-ACC-002",
                            Status = "Actif",
                            SupplierId = 3,
                            Weight = 0.40000000000000002
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            GrossMargin = 64.099999999999994,
                            Name = "Lampe frontale 300 lumens",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 14.0,
                            PriceToSell = 39.0,
                            Sku = "NC-ACC-003",
                            Status = "Actif",
                            SupplierId = 1,
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            GrossMargin = 59.200000000000003,
                            Name = "Ensemble vaisselle 4 pers.",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 20.0,
                            PriceToSell = 49.0,
                            Sku = "NC-ACC-004",
                            Status = "Actif",
                            SupplierId = 2,
                            Weight = 1.2
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            GrossMargin = 59.399999999999999,
                            Name = "Filtre a eau compact",
                            PaybackToSupplier = 0.050000000000000003,
                            PriceToBuy = 28.0,
                            PriceToSell = 69.0,
                            Sku = "NC-ACC-005",
                            Status = "Actif",
                            SupplierId = 1,
                            Weight = 0.69999999999999996
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            GrossMargin = 61.5,
                            Name = "Couteau multifonction",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 15.0,
                            PriceToSell = 39.0,
                            Sku = "NC-ACC-006",
                            Status = "Actif",
                            SupplierId = 4,
                            Weight = 0.5
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            GrossMargin = 56.899999999999999,
                            Name = "Montre GPS plein air",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 120.0,
                            PriceToSell = 279.0,
                            Sku = "NC-ELE-001",
                            Status = "Actif",
                            SupplierId = 7,
                            Weight = 0.90000000000000002
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            GrossMargin = 55.700000000000003,
                            Name = "Chargeur solaire 20W",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 35.0,
                            PriceToSell = 79.0,
                            Sku = "NC-ELE-002",
                            Status = "Actif",
                            SupplierId = 7,
                            Weight = 0.59999999999999998
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            GrossMargin = 62.5,
                            Name = "Boussole de précision",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 9.0,
                            PriceToSell = 24.0,
                            Sku = "NC-ELE-003",
                            Status = "Actif",
                            SupplierId = 2,
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            GrossMargin = 55.100000000000001,
                            Name = "Radio météo portable",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 22.0,
                            PriceToSell = 49.0,
                            Sku = "NC-ELE-004",
                            Status = "Actif",
                            SupplierId = 7,
                            Weight = 0.80000000000000004
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            GrossMargin = 56.0,
                            Name = "Lampe USB rechargeable",
                            PaybackToSupplier = 0.040000000000000001,
                            PriceToBuy = 11.0,
                            PriceToSell = 25.0,
                            Sku = "NC-ELE-005",
                            Status = "Actif",
                            SupplierId = 7,
                            Weight = 0.29999999999999999
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AverageDeliveryTime")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDeliveryTime = "1 jour",
                            Code = "AX",
                            Discount = 0,
                            Name = "AventureX"
                        },
                        new
                        {
                            Id = 2,
                            AverageDeliveryTime = "5 jour",
                            Code = "TS",
                            Discount = 0,
                            Name = "TrekSupply"
                        },
                        new
                        {
                            Id = 3,
                            AverageDeliveryTime = "6 jour",
                            Code = "MN",
                            Discount = 0,
                            Name = "MontNord"
                        },
                        new
                        {
                            Id = 4,
                            AverageDeliveryTime = "3 jour",
                            Code = "NP",
                            Discount = 0,
                            Name = "NordPack"
                        },
                        new
                        {
                            Id = 5,
                            AverageDeliveryTime = "4 jour",
                            Code = "NW",
                            Discount = 0,
                            Name = "NordWear"
                        },
                        new
                        {
                            Id = 6,
                            AverageDeliveryTime = "2 jour",
                            Code = "AL",
                            Discount = 0,
                            Name = "ArcticLine"
                        },
                        new
                        {
                            Id = 7,
                            AverageDeliveryTime = "2 jour",
                            Code = "TT",
                            Discount = 0,
                            Name = "TechTrail"
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.User.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tentes & abris"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sacs & portage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vetements techniques"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accessoires & cuisine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Electronique & navigation"
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.User.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SatisfactionLevel")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "144 rue de paul, Lévis, Qc, Canada",
                            Email = "paul@paul.ca",
                            Name = "Paul",
                            Password = "Paul123",
                            Phone = "418-878-4090",
                            Type = "particulier"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 rue du kayak, Montréal, Qc, Canada",
                            Email = "kayak@kayak.ca",
                            Name = "KayakManiac",
                            Password = "Kayak123",
                            Phone = "418-878-4990",
                            Type = "entreprise"
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.User.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "marc123@gmail.com",
                            HireDate = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Marc",
                            Password = "marc123*",
                            PhoneNumber = "418-882-8636",
                            Role = "Employee",
                            Surname = "Leblond"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "jean123@gmail.com",
                            HireDate = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Jean",
                            Password = "jean123*",
                            PhoneNumber = "418-882-8646",
                            Role = "Manager",
                            Surname = "Laronde"
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "money@gmail.com",
                            HireDate = new DateTime(2025, 11, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Arjean",
                            Password = "money123*",
                            PhoneNumber = "418-182-8646",
                            Role = "Accountant",
                            Surname = "Labonde"
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.Product", b =>
                {
                    b.HasOne("Nordik_Aventure.Objects.Models.User.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nordik_Aventure.Objects.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
