// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nordik_Aventure;

#nullable disable

namespace Nordik_Aventure.Migrations
{
    [DbContext(typeof(NordikAventureContext))]
    partial class NordikAventureContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.User.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tentes & abris"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sacs & portage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vetements techniques"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accessoires & cuisine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Electronique & navigation"
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.User.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SatisfactionLevel")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "144 rue de paul, Lévis, Qc, Canada",
                            Email = "paul@paul.ca",
                            Name = "Paul",
                            Password = "Paul123",
                            Phone = "418-878-4090",
                            Type = "particulier"
                        },
                        new
                        {
                            Id = 2,
                            Address = "123 rue du kayak, Montréal, Qc, Canada",
                            Email = "kayak@kayak.ca",
                            Name = "KayakManiac",
                            Password = "Kayak123",
                            Phone = "418-878-4990",
                            Type = "entreprise"
                        });
                });

            modelBuilder.Entity("Nordik_Aventure.Objects.Models.User.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmailAddress = "marc123@gmail.com",
                            HireDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Marc",
                            Password = "marc123*",
                            PhoneNumber = "418-882-8636",
                            Role = "Employee",
                            Surname = "Leblond"
                        },
                        new
                        {
                            Id = 2,
                            EmailAddress = "jean123@gmail.com",
                            HireDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Jean",
                            Password = "jean123*",
                            PhoneNumber = "418-882-8646",
                            Role = "Manager",
                            Surname = "Laronde"
                        },
                        new
                        {
                            Id = 3,
                            EmailAddress = "money@gmail.com",
                            HireDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "Arjean",
                            Password = "money123*",
                            PhoneNumber = "418-182-8646",
                            Role = "Accountant",
                            Surname = "Labonde"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
